Quiz = [
{ question: `Bond prices and interest rests have an inverse relationship as rates go up, Bond prices will tend to go: `,
multiple_choice: ['Down',
  'Up',
  'Stay the same',
  'To the fair'],
answer: 'Down',
},

{ question: 'Which of the four financial assets has the least risk: A stock with a dividend yield of 20%, A stock with the yield of 2%, A coupon bond, 100,000 in monopoly money in a 5% CD?',
multiple_choice: ['A stock with a dividend yield of 20%',
  'A stock with a dividend yield of 2%',
  'A coupon bond',
  '100,000 in monopoly money in a 5% CD'],
answer: 'A coupon bond'

},
{ question: 'What is the alpha of a financial instrument?',
multiple_choice: ['The return in excess of the market benchmark',
  'The measure of the market dominance',
  'The likelihood that a stock will pay dividend',
  'It’s return in the first year’'],
answer: 'The return in excess of the market benchmark',
},
{ question: 'When inflation rises, federal interest rates are likely to?',
multiple_choice: ['Go down',
  'Go up',
  'Stay the same',
  'Slide to right and cha cha real smooth',
  'None of the above'
  ],
answer: 'Go Up',
},
{ question: 'Interest rate risk is the risk that, opportunity cost will outweigh the benefits of holding an asset as interest rates fluctuate. What assets should you avoid the most in order to manage this risk?',
multiple_choice: ['High yield dividend stocks',
  'Long term interest bearing bonds',
  'Zero coupon bonds',
  'Bags of straw'],
answer: 'Long term interest bearing bonds',
},
{ question: 'To diversify your investment portfolio what must you take into consideration?',
multiple_choice: ['Marketing of companies',
  'Systemic risk',
  'Negative correlations between industries',
  'How large each alpha is in a given portfolio'],
answer: 'Negative correlations between industries',
},
{ question: 'Market beta is 1, What is the beta of an investment?',
multiple_choice: ['The measure of volatility ',
  'A number indicating how weak it is',
  'Its return',
  'None of the above'],
answer: 'The measure of volatility',
},
{ question: 'What is the goal of diversification? ',
multiple_choice: ['To maximize returns',
  'To spread risk evenly across investments',
  'Reduce risk',
  'To reduce returns and risk',
  'To lower operational costs'],
answer: 'Reduce risk',
},
{ question: 'What is idiosyncratic risk?',
multiple_choice: ['Risk that your financial advisor will make idiotic mistakes',
  'The risk specific to the company or sector or class of asset',
  'The risk that make a company quirky',
  'Risks specific to an industry'],
answer: 'The risk specific to the company or sector or class of asset',
},
{ question: 'You are in a search for a loan to purchase a new house. One of the requirements for the loan is a DTI ratio of 33%, your income is about $5,000 per month, How much debt can you be approved of?',
multiple_choice: ['~24000 per year',
  '20,000',
  '15,000',
  '~20,000',
  '~40000'],
answer: '~20,000',
}
]

